name: utopia-feed

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "16380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 20
